config/routes.rb
Cheezburger::Application.routes.draw do
  devise_for :views

  devise_for :users

  resources :beverages

  resources :orders

  resources :side_dishes

  resources :burgers

   root :to => 'orders#index'

end

app/models/burger.rb
class Burger < ActiveRecord::Base
  belongs_to :order
  attr_accessible :bun, :cheese, :meat, :order, :order_id
  validates :bun, :presence => true

  #scope :vegetarians, where(meat: "Veggie")

  attr_accessor :new_customer_name
  before_save :create_order_from_name

  set_inheritance_column "not_sti"

  def create_order_from_name
  	create_order(:customer => new_customer_name) unless new_customer_name.blank?
  end  
end

app/controllers/burgers_controller.rb
class BurgersController < ApplicationController
  # GET /burgers
  # GET /burgers.json
  def index
    @burgers = Burger.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @burgers }
    end
  end

  # GET /burgers/1
  # GET /burgers/1.json
  def show
    @burger = Burger.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @burger }
    end
  end

  # GET /burgers/new
  # GET /burgers/new.json
  def new
    @burger = Burger.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @burger }
    end
  end

  # GET /burgers/1/edit
  def edit
    @burger = Burger.find(params[:id])
  end

  # POST /burgers
  # POST /burgers.json
  def create
    @burger = Burger.new(params[:burger])

    respond_to do |format|
      if @burger.save
        format.html { redirect_to @burger, notice: 'Burger was successfully created.' }
        format.json { render json: @burger, status: :created, location: @burger }
      else
        format.html { render action: "new" }
        format.json { render json: @burger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /burgers/1
  # PUT /burgers/1.json
  def update
    @burger = Burger.find(params[:id])

    respond_to do |format|
      if @burger.update_attributes(params[:burger])
        format.html { redirect_to @burger, notice: 'Burger was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @burger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /burgers/1
  # DELETE /burgers/1.json
  def destroy
    @burger = Burger.find(params[:id])
    @burger.destroy

    respond_to do |format|
      format.html { redirect_to burgers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/burgers_helper.rb
module BurgersHelper
end

app/views/burgers/_form.html.erb
<style type="text/css">
.hidden { diplay: none; }
.unhidden { display: block;}
</style>

<%= form_for(@burger) do |f| %>
  <% if @burger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@burger.errors.count, "error") %> prohibited this burger from being saved:</h2>

      <ul>
      <% @burger.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br>

<div class="row">
  <div class="span3 offset1">
  <a href="javascript:unhide('helptext');" class="btn btn-info" id="helpbtn">Confused?</a>
  </div>
</div>

<div class="row">
  <div class="span3 offset1">
  <div id="helptext" class="hidden">
  Select a bun, meat, and cheese for the burger.Then add the burger to an existing order or create a new one.
  </div>
  </div>
</div>

    <script type="text/javascript">
    function unhide(divID) {
      var item = document.getElementById(divID);
      if (item) {
        item.className=(item.className=='hidden')?'unhidden':'hidden';
      }
    }
    </script>

  <div class="row">
    <div class="span3 offset1"
    <p><h4>Select meat</h4></p>
   <label class="radio">
    <%= f.radio_button(:meat, "beef") %>
    <%= f.label(:meat, "Beef") %>
       </label>
        <label class="radio">
    <%= f.radio_button(:meat, "turkey") %>
    <%= f.label(:meat, "Turkey") %>
       </label>
        <label class="radio">
     <%= f.radio_button(:meat, "bison") %>
    <%= f.label(:meat, "Bison") %>
       </label>
        <label class="radio">
    <%= f.radio_button(:meat, "ostrich") %>
    <%= f.label(:meat, "Ostrich") %>
       </label>
        <label class="radio">
     <%= f.radio_button(:meat, "veggie") %>
    <%= f.label(:meat, "Veggie") %>  
      </label>

  <br>
  
     <p><h4>Select cheese</h4></p>
    <label class="radio">
    <%= f.radio_button(:cheese, "swiss") %>
    <%= f.label(:swiss, "Swiss") %>
     </label>
     <label class="radio">
    <%= f.radio_button(:cheese, "cheddar") %>
    <%= f.label(:swiss, "Cheddar") %>
     </label>
     <label class="radio">
    <%= f.radio_button(:cheese, "prov") %>
    <%= f.label(:swiss, "Provolone") %>
     </label>
     <label class="radio">
    <%= f.radio_button(:cheese, "amer") %>
    <%= f.label(:swiss, "American") %>
  </label>


  <br>
 
   <p><h4>Select bun</h4></p>
    <label class="radio">
    <%= f.radio_button(:bun, "white") %>
    <%= f.label(:bun, "White") %>
     </label>
     <label class="radio">
    <%= f.radio_button(:bun, "wheat") %>
    <%= f.label(:bun, "Wheat") %>
     </label>
     <label class="radio">
    <%= f.radio_button(:bun, "onion") %>
    <%= f.label(:bun, "Onion") %>
     </label>
     <label class="radio">
    <%= f.radio_button(:bun, "none") %>
    <%= f.label(:bun, "Skip the carbs") %>
  </label>


  <br>

  </div>
</div>

<div class="row">
  <div class = "span5 offset1">
   <p><h4>Add to order:</h4></p>
    <%= f.collection_select :order_id,
      Order.all, :id, :customer, :prompt => "Select order"%>
       <%= link_to "Create new order", new_order_path %><br />
  </div>
</div>
  
  <div class="row">
    <div class="span3 offset1">
     <div class="form-actions">
      <%= f.submit class: "btn btn-primary"%> 
      </div>
      
    </div>
  </div>
    
 
  
  
<% end %>

app/views/burgers/edit.html.erb
<h1>Editing burger</h1>

<%= render 'form' %>

<%= link_to 'Show', @burger %> |
<%= link_to 'Back', burgers_path %>

app/views/burgers/index.html.erb
<h1>Listing burgers</h1>

<table>
  <tr>
    <th>Meat</th>
    <th>Cheese</th>
    <th>Bun</th>
    <th>Order</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @burgers.each do |burger| %>
  <tr>
    <td><%= burger.meat %></td>
    <td><%= burger.cheese %></td>
    <td><%= burger.bun %></td>
    <td><%= burger.order %></td>
    <td><%= link_to 'Show', burger %></td>
    <td><%= link_to 'Edit', edit_burger_path(burger) %></td>
    <td><%= link_to 'Destroy', burger, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Burger', new_burger_path %>

app/views/burgers/new.html.erb
<h1>New burger</h1>

<%= render 'form' %>

<%= link_to 'Back', burgers_path %>

app/views/burgers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Meat:</b>
  <%= @burger.meat %>
</p>

<p>
  <b>Cheese:</b>
  <%= @burger.cheese %>
</p>

<p>
  <b>Bun:</b>
  <%= @burger.bun %>
</p>

<p>
  <b>Order:</b>
  <%= @burger.order %>
</p>


<%= link_to 'Edit', edit_burger_path(@burger) %> |
<%= link_to 'Back', burgers_path %>