config/routes.rb
Cheezburger::Application.routes.draw do
  devise_for :views

  devise_for :users

  resources :beverages

  resources :orders

  resources :side_dishes

  resources :burgers

   root :to => 'orders#index'

end

app/models/beverage.rb
class Beverage < ActiveRecord::Base
  belongs_to :order
  attr_accessible :size, :type, :order, :order_id
  validates :size, :type, :presence => true

  set_inheritance_column "not_sti"
end

app/controllers/beverages_controller.rb
class BeveragesController < ApplicationController
  # GET /beverages
  # GET /beverages.json
  def index
    @beverages = Beverage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @beverages }
    end
  end

  # GET /beverages/1
  # GET /beverages/1.json
  def show
    @beverage = Beverage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @beverage }
    end
  end

  # GET /beverages/new
  # GET /beverages/new.json
  def new
    @beverage = Beverage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @beverage }
    end
  end

  # GET /beverages/1/edit
  def edit
    @beverage = Beverage.find(params[:id])
  end

  # POST /beverages
  # POST /beverages.json
  def create
    @beverage = Beverage.new(params[:beverage])

    respond_to do |format|
      if @beverage.save
        format.html { redirect_to @beverage, notice: 'Beverage was successfully created.' }
        format.json { render json: @beverage, status: :created, location: @beverage }
      else
        format.html { render action: "new" }
        format.json { render json: @beverage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /beverages/1
  # PUT /beverages/1.json
  def update
    @beverage = Beverage.find(params[:id])

    respond_to do |format|
      if @beverage.update_attributes(params[:beverage])
        format.html { redirect_to @beverage, notice: 'Beverage was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @beverage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beverages/1
  # DELETE /beverages/1.json
  def destroy
    @beverage = Beverage.find(params[:id])
    @beverage.destroy

    respond_to do |format|
      format.html { redirect_to beverages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/beverages_helper.rb
module BeveragesHelper
end

app/views/beverages/_form.html.erb
<%= form_for(@beverage) do |f| %>
  <% if @beverage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beverage.errors.count, "error") %> prohibited this beverage from being saved:</h2>

      <ul>
      <% @beverage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<br>


  <div class="row">
    <div class="span3 offset1"
    <p><h4>Select beverage</h4></p>
   <label class="radio">
    <%= f.radio_button(:type, "coke") %>
    <%= f.label(:type, "Coke") %>
   <%= f.radio_button(:type, "coke_z") %>
    <%= f.label(:type, "Coke Zero") %>  
    <%= f.radio_button(:type, "sprite") %>
    <%= f.label(:type, "Sprite") %>
    <%= f.radio_button(:type, "rootb") %>
    <%= f.label(:type, "Root Beer") %>    
    <%= f.radio_button(:type, "ginger") %>
    <%= f.label(:type, "Ginger Ale") %> 
    <%= f.radio_button(:type, "mtd") %>
    <%= f.label(:type, "Mountain Dew") %>
    <%= f.radio_button(:type, "dmtd") %>
    <%= f.label(:type, "Diet Mountain Dew") %>
    <%= f.radio_button(:type, "lemonade") %>
    <%= f.label(:type, "Lemonade") %>       
      </label>

  <br>


<p><h4>Select size</h4></p>
    <label class="radio">
    <%= f.radio_button(:size, "small") %>
    <%= f.label(:size, "Small") %>
    <%= f.radio_button(:size, "med") %>
    <%= f.label(:size, "Medium") %>
    <%= f.radio_button(:size, "large") %>
    <%= f.label(:size, "Large") %>
    <%= f.radio_button(:size, "xl") %>
    <%= f.label(:size, "Extra Large") %>
  </label>

  <br>

    <%= f.collection_select :order_id,
      Order.all, :id, :customer, :prompt => "Select order"%><br />

       <%= link_to "Create new order", new_order_path %>

  <div class="form-actions">
    <%= f.submit class: "btn btn-primary"%>
  </div>




 

</div>
</div>


<% end %>

app/views/beverages/edit.html.erb
<h1>Editing beverage</h1>

<%= render 'form' %>

<%= link_to 'Show', @beverage %> |
<%= link_to 'Back', beverages_path %>

app/views/beverages/index.html.erb
<h1>Listing beverages</h1>

<table>
  <tr>
    <th>Type</th>
    <th>Size</th>
    <th>Order</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @beverages.each do |beverage| %>
  <tr>
    <td><%= beverage.type %></td>
    <td><%= beverage.size %></td>
    <td><%= beverage.order %></td>
    <td><%= link_to 'Show', beverage %></td>
    <td><%= link_to 'Edit', edit_beverage_path(beverage) %></td>
    <td><%= link_to 'Destroy', beverage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Beverage', new_beverage_path %>

app/views/beverages/new.html.erb
<h1>New beverage</h1>

<%= render 'form' %>

<%= link_to 'Back', beverages_path %>

app/views/beverages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Type:</b>
  <%= @beverage.type %>
</p>

<p>
  <b>Size:</b>
  <%= @beverage.size %>
</p>

<p>
  <b>Order:</b>
  <%= @beverage.order %>
</p>


<%= link_to 'Edit', edit_beverage_path(@beverage) %> |
<%= link_to 'Back', beverages_path %>