config/routes.rb
Cheezburger::Application.routes.draw do
  devise_for :views

  devise_for :users

  resources :beverages

  resources :orders

  resources :side_dishes

  resources :burgers

   root :to => 'orders#index'

end

app/models/side_dish.rb
class SideDish < ActiveRecord::Base
  belongs_to :order
  attr_accessible :type, :order, :order_id
  validates :type, :presence => true

  set_inheritance_column "not_sti"
end

app/controllers/side_dishes_controller.rb
class SideDishesController < ApplicationController
  # GET /side_dishes
  # GET /side_dishes.json
  def index
    @side_dishes = SideDish.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @side_dishes }
    end
  end

  # GET /side_dishes/1
  # GET /side_dishes/1.json
  def show
    @side_dish = SideDish.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @side_dish }
    end
  end

  # GET /side_dishes/new
  # GET /side_dishes/new.json
  def new
    @side_dish = SideDish.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @side_dish }
    end
  end

  # GET /side_dishes/1/edit
  def edit
    @side_dish = SideDish.find(params[:id])
  end

  # POST /side_dishes
  # POST /side_dishes.json
  def create
    @side_dish = SideDish.new(params[:side_dish])

    respond_to do |format|
      if @side_dish.save
        format.html { redirect_to @side_dish, notice: 'Side dish was successfully created.' }
        format.json { render json: @side_dish, status: :created, location: @side_dish }
      else
        format.html { render action: "new" }
        format.json { render json: @side_dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /side_dishes/1
  # PUT /side_dishes/1.json
  def update
    @side_dish = SideDish.find(params[:id])

    respond_to do |format|
      if @side_dish.update_attributes(params[:side_dish])
        format.html { redirect_to @side_dish, notice: 'Side dish was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @side_dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /side_dishes/1
  # DELETE /side_dishes/1.json
  def destroy
    @side_dish = SideDish.find(params[:id])
    @side_dish.destroy

    respond_to do |format|
      format.html { redirect_to side_dishes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/side_dishes_helper.rb
module SideDishesHelper
end

app/views/side_dishes/_form.html.erb
<%= form_for(@side_dish) do |f| %>
  <% if @side_dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@side_dish.errors.count, "error") %> prohibited this side_dish from being saved:</h2>

      <ul>
      <% @side_dish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="span3 offset1">
 <p><h4>Select side</h4></p>
    <label class="radio">
    <%= f.radio_button(:type, "fries") %>
    <%= f.label(:type, "Fries") %>
    <%= f.radio_button(:type, "fruit") %>
    <%= f.label(:type, "Fruit") %>
    <%= f.radio_button(:type, "macncheese") %>
    <%= f.label(:type, "Mac n Cheese") %>
    <%= f.radio_button(:type, "salad") %>
    <%= f.label(:type, "Salad") %>
  </label>


  <br>

   <p><h4>Add to order:</h4></p>
    <%= f.collection_select :order_id,
      Order.all, :id, :customer, :prompt => "Select order"%><br />

           <%= link_to "Create new order", new_order_path %>

  <div class="form-actions">
    <%= f.submit class: "btn btn-primary"%>
  </div>
</div>
</div>
<% end %>

app/views/side_dishes/edit.html.erb
<h1>Editing side_dish</h1>

<%= render 'form' %>

<%= link_to 'Show', @side_dish %> |
<%= link_to 'Back', side_dishes_path %>

app/views/side_dishes/index.html.erb
<h1>Listing side_dishes</h1>

<table>
  <tr>
    <th>Type</th>
    <th>Order</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @side_dishes.each do |side_dish| %>
  <tr>
    <td><%= side_dish.type %></td>
    <td><%= side_dish.order %></td>
    <td><%= link_to 'Show', side_dish %></td>
    <td><%= link_to 'Edit', edit_side_dish_path(side_dish) %></td>
    <td><%= link_to 'Destroy', side_dish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Side dish', new_side_dish_path %>

app/views/side_dishes/new.html.erb
<h1>New side_dish</h1>

<%= render 'form' %>

<%= link_to 'Back', side_dishes_path %>

app/views/side_dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Type:</b>
  <%= @side_dish.type %>
</p>

<p>
  <b>Order:</b>
  <%= @side_dish.order %>
</p>


<%= link_to 'Edit', edit_side_dish_path(@side_dish) %> |
<%= link_to 'Back', side_dishes_path %>